apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:cJBiwhztC58ZjHsEw7PeHWAr5dQ0WvzJbg==,iv:bx1GvZGylw4uayRQN0T4AK5mkcEWG4Kn2LfHJuRXAuo=,tag:SCEKgarGpbWlOpwT3DQnXA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:Ps8Mj1Y+q8WmH3Y3+Q47j7JdmhnapJ0VYjpl4TrYloOycJh0nw==,iv:zF7rUyiOUrUQ8N0TEySvwRo2gOMXw1LOMNe5piuVS3U=,tag:AggJZ0sE/G+UeqazXPPluw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:3TtCXEvjGLhfHHuae8FQKD4af3Q=,iv:M4b7bVYTDQz78FL+kHkkVAbxRi88PSphjCva32jx9D0=,tag:7sveDlnLEguxy6U82XfhvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wc6fcmsdunsh6tqpxx3jjzl9lw3h6rslspnn9mphdtu03h8y7aqschpv07
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdUNQZFlROVZYYlBSOU5O
            UkoyTkJVek9UcFVhK3RiRnhZaExLaVRDRmdRClA1blpzYWkzUnNKQlBENENucmVE
            cUxCa2VqVmZMNUNCREZQM01FTHdxdk0KLS0tIE90SEg3UVMwMEhpVVhONWZYS1Y2
            TDNEZUVaQXhUZVdHNlhMTG1JclRsTHcKljWnBcNZXmd8mO1XQ9rXtlT/ijGmeXn6
            O5HK7kPZYLvAnq1a8y1NMQnVmb7Dnfxd3Eauek44uiK9LGN1fI4gxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-11T03:19:53Z"
    mac: ENC[AES256_GCM,data:1BPqTWxyJBj9C2dfJ1EHBIbdzhz3pwgZeG4dXwIm0m2VLJfGmDwO6bzCbZ3Ai/zxZeUbxBnb2ndFx1GecDlxiNEcBffvriBfqo7Tj6EXQlhCnUGGkGBtTTokfIXkO2xcBiW0FDyG7czni451T/aw8xYn5CiTTtgXBhhbHEPJigI=,iv:VVf+3y0W0aK8l/YyIvPGG1IyATu2wQL3qYhV/Qc9IoA=,tag:+QEOWDYOSdnStaup2lse8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
