apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:YnohOUyP0sn9/OXRiItHTpAxwluTHhmzr/9tU42bkPRb6CD1Tg==,iv:jIk65Lo/rhuFLvWT5OA98hnmIlj4v1ygi1XsrS/B0g4=,tag:bXSGP8zRoXrTzCEEcS7ElA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wc6fcmsdunsh6tqpxx3jjzl9lw3h6rslspnn9mphdtu03h8y7aqschpv07
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSlJvSHlTWHBQd3JXTWxW
            VWx2QjVNTHdXRVFaZW1DcG5XTmVkTlo0UDI0CnJ0QVRIRmNhRlFwNlZYb0dXelBj
            RWVXUnUzSHNGTG84dXZnOWIzaWZuUEkKLS0tIFVHOHNTdzFPSTJKVWhHa2xkRzFx
            RUtBNEhYRjVpMVdIUmtpeWFnRkh0eGsKqagRSkALqomCVmyjugKr09Cn9W18I05/
            m1XeszRmLEweXwdZbGNb5muJ2w86rYmDWSLQz3E9WS5f7f9ieNTz0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-11T03:19:53Z"
    mac: ENC[AES256_GCM,data:hIdlXZw0sV8XfQO6DXQtub3mvdqmXVPUv9KMt/NU5GUOgHLPcccBdHfgDTRxIgZtiKJh7fwyHxRxya7A8+FQwy+ZUyYFQALNWzhN2OyF2lgcntzITDVdg6k6c1YMomavbTuD8Ag9GEkfhJv0irhKWucF32X10tz9H2uHoKZdfLE=,iv:bi8VHpqDBil4Hs75Rgjip/98BE78mYqs+v1L8hGNX4s=,tag:J0H3sjpgv1P+qa15RASHtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
